controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
accueil:
    path: /
    controller: App\Controller\AccueilController::index

# config/routes.yaml
contact:
    path: /contact
    controller: App\Controller\ContactController::index

# config/routes.yaml
articles:
    path: /articles
    controller: App\Controller\ArticleController::index

# config/routes.yaml

recherche:
    resource: ../src/Controller/RechercheController.php
    type: annotation

# config/routes.yaml

contact_submit:
    path: '/contact/submit'
    controller: 'App\Controller\ContactController::submit'
    methods: ['POST']

# config/routes.yaml
categorie_list:
    path: '/categories'
    controller: 'App\Controller\CategorieTestController::create'

categorie_nouveau:
    path: '/categorie/nouveau'
    controller: 'App\Controller\CategorieController::nouveau'
    methods: ['GET', 'POST']

liste_categories:
    path: '/categorie/liste'
    controller: 'App\Controller\CategorieController::liste'
    methods: ['GET']

categorie_edition:
    path: '/categorie/edition/{id}'
    controller: 'App\Controller\CategorieController::edition'

categorie_suppression:
    path: '/categorie/suppression/{id}'
    controller: 'App\Controller\CategorieController::suppression'