controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# config/routes.yaml
articles:
    path: /articles
    controller: App\Controller\ArticleController::index

# config/routes.yaml

recherche:
    resource: ../src/Controller/RechercheController.php
    type: annotation

# config/routes.yaml

contact_submit:
    path: '/contact/submit'
    controller: 'App\Controller\ContactController::submit'
    methods: ['POST']

# config/routes.yaml
categorie_list:
    path: '/categories'
    controller: 'App\Controller\CategorieTestController::create'

categorie_nouveau:
    path: '/categorie/nouveau'
    controller: 'App\Controller\CategorieController::nouveau'
    methods: ['GET', 'POST']

liste_categories:
    path: '/categorie/liste'
    controller: 'App\Controller\CategorieController::liste'
    methods: ['GET']

categorie_edition:
    path: '/categorie/edition/{id}'
    controller: 'App\Controller\CategorieController::edition'

categorie_suppression:
    path: '/categorie/suppression/{id}'
    controller: 'App\Controller\CategorieController::suppression'

# config/routes.yaml

app_article_crud_index:
    path: /article/crud/
    controller: App\Controller\ArticleCrudController::index
    methods: ['GET']

app_article_crud_new:
    path: /article/crud/new
    controller: App\Controller\ArticleCrudController::new
    methods: ['GET', 'POST']

app_article_crud_show:
    path: /article/crud/{id}
    controller: App\Controller\ArticleCrudController::show
    methods: ['GET']

app_article_crud_edit:
    path: /article/crud/{id}/edit
    controller: App\Controller\ArticleCrudController::edit
    methods: ['GET', 'POST']

app_article_crud_delete:
    path: /article/crud/{id}
    controller: App\Controller\ArticleCrudController::delete
    methods: ['POST']
